on:
  push:
    branches:
      - master
name: Package and run Proact on master branch
jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: npm install
      uses: actions/npm@master
      with:
        args: install
    - name: install cloudguard protego package
      uses: actions/npm@master
      with:
        args: install -g https://artifactory.app.protego.io/cloudguard-serverless-plugin.tgz
    - name: serverless package
      uses: serverless/github-action@master
      with:
        args: package
      env:
        SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
        # or if using AWS creds directly
        # AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        # AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
