# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-18.04

    strategy:
      matrix:
        node-version: [12.18.1]

    steps:
      - uses: actions/checkout@v2
      #- uses: serverless/github-action@master
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - shell: bash
        env:
          CG_KEY: ${{secrets.CGW_SERVERLESS}}
        run: "echo \"{\n\t\"cloudguardAccessToken\": \"$CG_KEY\"\n}\" > cloudguard-config.json"
      - name: Install node modules
        run: |
          npm i https://artifactory.app.protego.io/cloudguard-serverless-plugin.tgz
          npm i serverless
          npm ci
          serverless package
